services:
  - type: web
    name: book-store
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGO_URI
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: PORT
        value: 10000
